import unittest
import time
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.select import Select
import random
import string


class employees(unittest.TestCase):
    status = '//datatable-row-wrapper[4]/datatable-body-row/div[2]/datatable-body-cell[6]/div/input'
    gender = '/html/body/app-root/app-dashboard/div/div/main/div/div/app-adminsettings/app-employee-form/div/div/div[2]/aw-wizard/div/aw-wizard-step[1]/form/div[1]/div[1]/div[5]/div/select'
    email = ''.join(random.sample(string.ascii_letters + string.digits, 15))
    role = '/html/body/app-root/app-dashboard/div/div/main/div/div/app-adminsettings/app-employee-form/div/div/div[2]/aw-wizard/div/aw-wizard-step[1]/form/div[1]/div[2]/div[2]/div/select'
    state = '/html/body/app-root/app-dashboard/div/div/main/div/div/app-adminsettings/app-employee-form/div/div/div[2]/aw-wizard/div/aw-wizard-step[1]/form/div[1]/div[2]/div[5]/div/select'
    mail = ''.join(random.sample(string.ascii_letters + string.digits, 15))
    site = '/html/body/app-root/app-dashboard/div/div/main/div/div/app-adminsettings/app-employee-form/div/div/div[2]/aw-wizard/div/aw-wizard-step[2]/form[1]/div[2]/div/div/div[1]/select'
    remove = '/html/body/app-root/app-dashboard/div/div/main/div/div/app-adminsettings/app-employee-form/div/div/div[2]/aw-wizard/div/aw-wizard-step[2]/form[1]/div[3]/div/div/div[3]/button/span'
    employment = '/html/body/app-root/app-dashboard/div/div/main/div/div/app-adminsettings/app-employee-form/div/div/div[2]/aw-wizard/div/aw-wizard-step[3]/form[1]/div/div/div[2]/div/select'
    bachelors = '/html/body/app-root/app-dashboard/div/div/main/div/div/app-adminsettings/app-employee-form/div/div/div[2]/aw-wizard/div/aw-wizard-step[2]/form[2]/div[2]/div/angular2-multiselect/div/div[2]/div[3]/div[4]/ul/li[1]'
    training = '/html/body/app-root/app-dashboard/div/div/main/div/div/app-adminsettings/app-employee-form/div/div/div[2]/aw-wizard/div/aw-wizard-step[2]/form[2]/div[3]/div/angular2-multiselect/div/div[2]/div[3]/div[4]/ul/li'
    abilities = '/html/body/app-root/app-dashboard/div/div/main/div/div/app-adminsettings/app-employee-form/div/div/div[2]/aw-wizard/div/aw-wizard-step[2]/form[2]/div[4]/div/angular2-multiselect/div/div[2]/div[3]/div[4]/ul/li'
    payment = '/html/body/app-root/app-dashboard/div/div/main/div/div/app-adminsettings/app-employee-form/div/div/div[2]/aw-wizard/div/aw-wizard-step[3]/form[1]/div/div/div[4]/div/select'
    leave = '/html/body/app-root/app-dashboard/div/div/main/div/div/app-adminsettings/app-employee-form/div/div/div[2]/aw-wizard/div/aw-wizard-step[3]/form[2]/div[2]/div/angular2-multiselect/div/div[1]/div'
    sick = '/html/body/app-root/app-dashboard/div/div/main/div/div/app-adminsettings/app-employee-form/div/div/div[2]/aw-wizard/div/aw-wizard-step[3]/form[2]/div[2]/div/angular2-multiselect/div/div[2]/div[3]/div[4]/ul/li[2]/label'
    edit = '/html/body/app-root/app-dashboard/div/div/main/div/div/app-adminsettings/app-employee/div/div/div[2]/ngx-datatable/div/datatable-body/datatable-selection/datatable-scroller/datatable-row-wrapper/datatable-body-row/div[2]/datatable-body-cell[7]/div/button'


    @classmethod
    def setUpClass(self):
        self.driver = webdriver.Chrome(ChromeDriverManager().install())
        self.driver.maximize_window()
        self.driver.implicitly_wait(15)
        self.driver.get("http://easyrogo.nestrait.com/")
        self.driver.find_element_by_name("username").click()
        self.driver.find_element_by_name("username").clear()
        self.driver.find_element_by_name("username").send_keys("jqu80496@zwoho.com")
        self.driver.find_element_by_name("password").click()
        self.driver.find_element_by_name("password").clear()
        self.driver.find_element_by_name("password").send_keys("Template999#")
        self.driver.find_element_by_xpath('//button[normalize-space()="SIGN IN"]').click()
        self.driver.find_element_by_link_text("Admin Settings").click()
        time.sleep(1)
        self.driver.find_element_by_link_text("Employees").click()

    def test_1_status(self):
        self.driver.find_element_by_xpath(self.status).click()
        self.driver.find_element_by_xpath('//button[normalize-space()="Ok"]').click()
        time.sleep(5)
        self.driver.find_element_by_xpath(self.status).click()
        self.driver.find_element_by_xpath('//button[normalize-space()="Ok"]').click()
        time.sleep(3)
        self.driver.find_element_by_xpath(self.status).click()
        self.driver.find_element_by_xpath('//button[normalize-space()="Cancel"]').click()
        time.sleep(2)

    def test_2_page_no(self):
        self.driver.find_element_by_link_text("2").click()
        self.driver.find_element_by_link_text("1").click()
        self.driver.execute_script("window.scrollTo(0, 0)")
        time.sleep(1)

    def test_3_add_employee(self):
        self.driver.find_element_by_xpath('//button[normalize-space()="ADD EMPLOYEE"]').click()
        self.driver.find_element_by_xpath('//button[normalize-space()="NEXT"]').click()
        time.sleep(2)
        self.driver.execute_script("window.scrollTo(0, 0)")
        self.driver.find_element_by_xpath("//input[@type='text']").click()
        self.driver.find_element_by_xpath("//input[@type='text']").clear()
        self.driver.find_element_by_xpath("//input[@type='text']").send_keys("Ram")
        self.driver.find_element_by_xpath("//div[3]/div/input").click()
        self.driver.find_element_by_xpath("//div[3]/div/input").clear()
        self.driver.find_element_by_xpath("//div[3]/div/input").send_keys("Yadav")
        self.driver.find_element_by_xpath("//div[4]/div/input").click()
        self.driver.find_element_by_xpath("//div[4]/div/input").clear()
        self.driver.find_element_by_xpath("//div[4]/div/input").send_keys("12 Jan 1978")
        Select(self.driver.find_element_by_xpath(self.gender)).select_by_visible_text("male")
        self.driver.find_element_by_xpath("//input[@type='email']").click()
        self.driver.find_element_by_xpath("//input[@type='email']").clear()
        self.driver.find_element_by_xpath("//input[@type='email']").send_keys("ramyadav@it.com")
        self.driver.find_element_by_xpath("//div[7]/div/input").click()
        self.driver.find_element_by_xpath("//div[7]/div/input").clear()
        self.driver.find_element_by_xpath("//div[7]/div/input").send_keys("9865432790")
        Select(self.driver.find_element_by_xpath(self.role)).select_by_visible_text("employee")
        self.driver.find_element_by_xpath("//div[2]/div[3]/div/input").click()
        self.driver.find_element_by_xpath("//div[2]/div[3]/div/input").clear()
        self.driver.find_element_by_xpath("//div[2]/div[3]/div/input").send_keys("Lazimpat")
        self.driver.find_element_by_xpath("//div[2]/div[4]/div/input").click()
        self.driver.find_element_by_xpath("//div[2]/div[4]/div/input").clear()
        self.driver.find_element_by_xpath("//div[2]/div[4]/div/input").send_keys("Kathmandu")
        Select(self.driver.find_element_by_xpath(self.state)).select_by_visible_text("Bagmati Zone")
        self.driver.find_element_by_xpath("//div[2]/div[6]/div/input").click()
        self.driver.find_element_by_xpath("//div[2]/div[6]/div/input").clear()
        self.driver.find_element_by_xpath("//div[2]/div[6]/div/input").send_keys("97540")
        time.sleep(2)

        self.driver.execute_script("window.scrollTo(0, 5)")
        time.sleep(1)
        self.driver.find_element_by_xpath('//button[normalize-space()="RESET"]').click()
        time.sleep(1)
        self.driver.execute_script("window.scrollTo(0, 0)")
        self.driver.find_element_by_xpath("//input[@type='text']").click()
        self.driver.find_element_by_xpath("//input[@type='text']").clear()
        self.driver.find_element_by_xpath("//input[@type='text']").send_keys("Hari")
        self.driver.find_element_by_xpath("//div[3]/div/input").click()
        self.driver.find_element_by_xpath("//div[3]/div/input").clear()
        self.driver.find_element_by_xpath("//div[3]/div/input").send_keys("dev")
        self.driver.find_element_by_xpath("//div[4]/div/input").click()
        self.driver.find_element_by_xpath("//div[4]/div/input").clear()
        self.driver.find_element_by_xpath("//div[4]/div/input").send_keys("1 Feb 1982")
        Select(self.driver.find_element_by_xpath(self.gender)).select_by_visible_text("male")
        self.driver.find_element_by_xpath("//input[@type='email']").click()
        self.driver.find_element_by_xpath("//input[@type='email']").clear()
        self.driver.find_element_by_xpath("//input[@type='email']").send_keys(self.email + "@gmail.com")
        self.driver.find_element_by_xpath("//div[7]/div/input").click()
        self.driver.find_element_by_xpath("//div[7]/div/input").clear()
        self.driver.find_element_by_xpath("//div[7]/div/input").send_keys("9865432790")
        Select(self.driver.find_element_by_xpath(self.role)).select_by_visible_text("employee")
        self.driver.find_element_by_xpath("//div[2]/div[3]/div/input").click()
        self.driver.find_element_by_xpath("//div[2]/div[3]/div/input").clear()
        self.driver.find_element_by_xpath("//div[2]/div[3]/div/input").send_keys("Lazimpat")
        self.driver.find_element_by_xpath("//div[2]/div[4]/div/input").click()
        self.driver.find_element_by_xpath("//div[2]/div[4]/div/input").clear()
        self.driver.find_element_by_xpath("//div[2]/div[4]/div/input").send_keys("Kathmandu")
        Select(self.driver.find_element_by_xpath(self.state)).select_by_visible_text("Gandaki Zone")
        self.driver.find_element_by_xpath("//div[2]/div[6]/div/input").click()
        self.driver.find_element_by_xpath("//div[2]/div[6]/div/input").clear()
        self.driver.find_element_by_xpath("//div[2]/div[6]/div/input").send_keys("97540")
        self.driver.execute_script("window.scrollTo(0, 5)")
        self.driver.find_element_by_xpath('//button[normalize-space()="NEXT"]').click()
        self.driver.find_element_by_xpath("(//button[normalize-space()='NEXT'])[2]").click()
        time.sleep(1)

        Select(self.driver.find_element_by_xpath(self.site)).select_by_visible_text("Claire Mooney")
        time.sleep(2)
        self.driver.find_element_by_xpath("(//button[normalize-space()='RESET'])[2]").click()
        time.sleep(2)
        Select(self.driver.find_element_by_xpath(self.site)).select_by_visible_text("NestraIT")
        self.driver.find_element_by_xpath('//button[normalize-space()="ADD Work Details and Abilities"]').click()
        time.sleep(2)
        self.driver.find_element_by_xpath(self.remove).click()
        time.sleep(2)
        self.driver.find_element_by_xpath('//button[normalize-space()="PREVIOUS"]').click()
        time.sleep(1)
        self.driver.execute_script("window.scrollTo(0, 5)")
        self.driver.find_element_by_xpath('//button[normalize-space()="NEXT"]').click()
        time.sleep(1)
        self.driver.find_element_by_xpath("(//button[normalize-space()='NEXT'])[2]").click()

        self.driver.find_element_by_xpath('//button[normalize-space()="AND NEXT"]').click()
        time.sleep(1)
        self.driver.find_element_by_xpath("//aw-wizard-step[3]/form/div/div/div/div/input").click()
        self.driver.find_element_by_xpath("//aw-wizard-step[3]/form/div/div/div/div/input").clear()
        self.driver.find_element_by_xpath("//aw-wizard-step[3]/form/div/div/div/div/input").send_keys("22 Jan 2022")
        Select(self.driver.find_element_by_xpath(self.employment)).select_by_visible_text("Permanent Full Time")
        time.sleep(1)
        self.driver.find_element_by_xpath("(//button[normalize-space()='RESET'])[3]").click()
        time.sleep(1)
        self.driver.find_element_by_xpath("//aw-wizard-step[3]/form/div/div/div/div/input").click()
        self.driver.find_element_by_xpath("//aw-wizard-step[3]/form/div/div/div/div/input").clear()
        self.driver.find_element_by_xpath("//aw-wizard-step[3]/form/div/div/div/div/input").send_keys("11 Feb 2022")
        Select(self.driver.find_element_by_xpath(self.employment)).select_by_visible_text("Permanent Full Time")
        self.driver.find_element_by_xpath("(//button[normalize-space()='PREVIOUS'])[2]").click()
        time.sleep(1)
        self.driver.find_element_by_xpath("(//button[normalize-space()='NEXT'])[2]").click()
        time.sleep(1)
        self.driver.find_element_by_xpath('//button[normalize-space()="AND NEXT"]').click()
        time.sleep(3)

    def test_4_save_close(self):
        self.driver.find_element_by_xpath("//input[@type='text']").click()
        self.driver.find_element_by_xpath("//input[@type='text']").clear()
        self.driver.find_element_by_xpath("//input[@type='text']").send_keys("Ram")
        self.driver.find_element_by_xpath("//div[2]/div/input").click()
        self.driver.find_element_by_xpath("//div[2]/div/input").clear()
        self.driver.find_element_by_xpath("//div[2]/div/input").send_keys("Raj")
        self.driver.find_element_by_xpath("//div[3]/div/input").click()
        self.driver.find_element_by_xpath("//div[3]/div/input").clear()
        self.driver.find_element_by_xpath("//div[3]/div/input").send_keys("Yadav")
        self.driver.find_element_by_xpath("//div[4]/div/input").send_keys("12 Jan 1978")
        Select(self.driver.find_element_by_xpath(self.gender)).select_by_visible_text("male")
        self.driver.find_element_by_xpath("//input[@type='email']").click()
        self.driver.find_element_by_xpath("//input[@type='email']").clear()
        self.driver.find_element_by_xpath("//input[@type='email']").send_keys(self.mail + "@gmail.com")
        self.driver.find_element_by_xpath("//div[7]/div/input").click()
        self.driver.find_element_by_xpath("//div[7]/div/input").clear()
        self.driver.find_element_by_xpath("//div[7]/div/input").send_keys("9865432790")
        Select(self.driver.find_element_by_xpath(self.role)).select_by_visible_text("employee")
        self.driver.find_element_by_xpath("//div[2]/div[3]/div/input").click()
        self.driver.find_element_by_xpath("//div[2]/div[3]/div/input").clear()
        self.driver.find_element_by_xpath("//div[2]/div[3]/div/input").send_keys("Lazimpat")
        self.driver.find_element_by_xpath("//div[2]/div[4]/div/input").click()
        self.driver.find_element_by_xpath("//div[2]/div[4]/div/input").clear()
        self.driver.find_element_by_xpath("//div[2]/div[4]/div/input").send_keys("Kathmandu")
        Select(self.driver.find_element_by_xpath(self.state)).select_by_visible_text("Bagmati Zone")
        self.driver.find_element_by_xpath("//div[2]/div[6]/div/input").click()
        self.driver.find_element_by_xpath("//div[2]/div[6]/div/input").clear()
        self.driver.find_element_by_xpath("//div[2]/div[6]/div/input").send_keys("97540")
        self.driver.execute_script("window.scrollTo(0, 5)")
        self.driver.find_element_by_xpath("//div[2]/div[2]/div/div/input").click()
        self.driver.find_element_by_xpath("//div[2]/div[2]/div/div/input").clear()
        self.driver.find_element_by_xpath("//div[2]/div[2]/div/div/input").send_keys("Chandra Guru")
        self.driver.find_element_by_xpath("//div[3]/div/div/input").click()
        self.driver.find_element_by_xpath("//div[3]/div/div/input").clear()
        self.driver.find_element_by_xpath("//div[3]/div/div/input").send_keys("Father")
        self.driver.find_element_by_xpath("//div[4]/div/div/input").click()
        self.driver.find_element_by_xpath("//div[4]/div/div/input").clear()
        self.driver.find_element_by_xpath("//div[4]/div/div/input").send_keys("98543457790")
        self.driver.find_element_by_xpath('//button[normalize-space()="NEXT"]').click()

        Select(self.driver.find_element_by_xpath(self.site)).select_by_visible_text("NestraIT")
        self.driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Departments'])[1]/following::div[4]").click()
        self.driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Adminstration'])[1]/following::label[1]").click()
        self.driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Qualification:'])[1]/following::div[4]").click()
        self.driver.find_element_by_xpath(self.bachelors).click()
        self.driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Employee: New'])[1]/following::ul[1]").click()
        self.driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Trainings:'])[1]/following::div[4]").click()
        self.driver.find_element_by_xpath(self.training).click()
        self.driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Employee: New'])[1]/following::ul[1]").click()
        self.driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Other Abilities Details:'])[1]/following::div[4]").click()
        self.driver.find_element_by_xpath(self.abilities).click()
        self.driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Employee: New'])[1]/following::ul[1]").click()
        self.driver.find_element_by_xpath("(//button[normalize-space()='NEXT'])[2]").click()

        self.driver.find_element_by_xpath('//button[normalize-space()="AND CLOSE"]').click()
        self.driver.find_element_by_xpath("//aw-wizard-step[3]/form/div/div/div/div/input").click()
        self.driver.find_element_by_xpath("//aw-wizard-step[3]/form/div/div/div/div/input").clear()
        self.driver.find_element_by_xpath("//aw-wizard-step[3]/form/div/div/div/div/input").send_keys("28 Dec 2021")
        Select(self.driver.find_element_by_xpath(self.employment)).select_by_visible_text("Permanent Full Time")
        Select(self.driver.find_element_by_xpath(self.payment)).select_by_visible_text("Salary")
        self.driver.find_element_by_xpath("//div[5]/div/input").click()
        self.driver.find_element_by_xpath("//div[5]/div/input").clear()
        self.driver.find_element_by_xpath("//div[5]/div/input").send_keys("45")
        self.driver.find_element_by_xpath("//aw-wizard-step[3]/form/div/div/div[6]/div/input").click()
        self.driver.find_element_by_xpath("//aw-wizard-step[3]/form/div/div/div[6]/div/input").clear()
        self.driver.find_element_by_xpath("//aw-wizard-step[3]/form/div/div/div[6]/div/input").send_keys("240000")
        self.driver.find_element_by_xpath(self.leave).click()
        self.driver.find_element_by_xpath(self.sick).click()
        self.driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Employee: New'])[1]/following::div[1]").click()
        self.driver.find_element_by_xpath('//button[normalize-space()="AND CLOSE"]').click()
        time.sleep(3)

    def test_5_add_close(self):
        self.driver.find_element_by_xpath('//button[normalize-space()="ADD EMPLOYEE"]').click()
        self.driver.execute_script("window.scrollTo(0, 5)")
        time.sleep(3)
        self.driver.find_element_by_xpath('//button[normalize-space()="CLOSE"]').click()
        time.sleep(2)

    def test_6_show_entries_export_CSV(self):
        Select(self.driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Show Entries'])[1]/following::select[1]")).select_by_visible_text("25")
        time.sleep(1)
        Select(self.driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Show Entries'])[1]/following::select[1]")).select_by_visible_text("10")
        time.sleep(2)
        self.driver.find_element_by_link_text("Export To CSV").click()
        time.sleep(3)


    def test_7_sorting(self):
        self.driver.find_element_by_xpath("//datatable-header-cell/div/span[2]").click()
        time.sleep(1)
        self.driver.find_element_by_xpath("//datatable-header-cell/div/span[2]").click()
        time.sleep(1)
        self.driver.find_element_by_xpath("//datatable-header-cell[2]/div/span[2]").click()
        time.sleep(1)
        self.driver.find_element_by_xpath("//datatable-header-cell[2]/div/span[2]").click()
        time.sleep(1)
        self.driver.find_element_by_xpath("//datatable-header-cell[3]/div/span[2]").click()
        time.sleep(1)
        self.driver.find_element_by_xpath("//datatable-header-cell[3]/div/span[2]").click()
        time.sleep(1)
        self.driver.find_element_by_xpath("//datatable-header-cell[4]/div/span[2]").click()
        time.sleep(1)
        self.driver.find_element_by_xpath("//datatable-header-cell[4]/div/span[2]").click()
        time.sleep(1)
        self.driver.find_element_by_xpath("//datatable-header-cell[5]/div/span[2]").click()
        time.sleep(1)
        self.driver.find_element_by_xpath("//datatable-header-cell[5]/div/span[2]").click()
        time.sleep(1)

    def test_8_search(self):
        self.driver.find_element_by_xpath("//input[@type='text']").click()
        self.driver.find_element_by_xpath("//input[@type='text']").clear()
        self.driver.find_element_by_xpath("//input[@type='text']").send_keys("est")
        time.sleep(2)

    def test_9_edit(self):
        self.driver.find_element_by_xpath(self.edit).click()
        self.driver.find_element_by_xpath('//button[normalize-space()="Work Details and Abilities"]').click()
        time.sleep(1)
        self.driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Qualification:'])[1]/following::div[4]").click()
        self.driver.find_element_by_xpath("/html/body/app-root/app-dashboard/div/div/main/div/div/app-adminsettings/app-employee/app-employee-personaldetails/div/div[2]/div[2]/div[2]/form/div[2]/div/angular2-multiselect/div/div[2]/div[3]/div[4]/ul/li[1]").click()
        self.driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::div[2]").click()
        time.sleep(1)
        self.driver.find_element_by_xpath('//button[normalize-space()="Save"]').click()
        time.sleep(3)
        self.driver.find_element_by_xpath('//button[normalize-space()="Back"]').click()
        time.sleep(2)



    @classmethod
    def tearDownClass(self):
        self.driver.close()
        print("test closed")


if __name__ == '__main__':
    unittest.main()
